package com.destrostudios.cards.shared.rules;

public enum AdvancedPrefilter {
    CREATURE_OR_NO_CREATURES,
    SOURCE,
    NOT_SOURCE,
    ALLY,
    NOT_ALLY,
    DAMAGED,
    NOT_DAMAGED,
    OWNER,
    OWNER_WHILE_ACTIVE,
    OPPONENT,
    DEFAULT_CAST_FROM_HAND_SPELL,
    SOURCE_DEFAULT_CAST_FROM_HAND_SPELL,
    SOURCE_HAND,
    SOURCE_CREATURE_CARD,
    SOURCE_SPELL_CARD,
    SOURCE_DRAGON,
    SOURCE_ALLY,
    SOURCE_NOT_ALLY,
}
