package com.destrostudios.cards.shared.rules;

public class AllCards {

    public static final String[] TEMPLATES = new String[] {
        "creatures/ancient_tree",
        "creatures/arandir",
        "creatures/army_commander",
        "creatures/artificial_guardian",
        "creatures/battle_cleric",
        "creatures/blademaster",
        "creatures/blessed_barbarian",
        "creatures/brave_soldier",
        "creatures/bronze_golem",
        "creatures/crazed_doctor",
        "creatures/dam",
        "creatures/divine_justicar",
        "creatures/emperor_tamarin",
        "creatures/fairy",
        "creatures/goblin_dentist",
        "creatures/goblin_hunter",
        "creatures/goblin_warhead_launcher",
        "creatures/golden_emperor",
        "creatures/good_boy",
        "creatures/grumpy_captain",
        "creatures/guardian_dragon",
        "creatures/injured_legend",
        "creatures/inspiring_angel",
        "creatures/legion_angel",
        "creatures/leviathan",
        "creatures/mounted_dwarf_warrior",
        "creatures/novice_paladin",
        "creatures/old_archer",
        "creatures/pebble",
        "creatures/plated_aradon",
        "creatures/shieldmaster",
        "creatures/sir_theodor_the_third",
        "creatures/terror_from_above",
        "creatures/tiny_dragon",
        "creatures/valkyrie",
        "creatures/young_inventor",
        "spells/bonfire",
        "spells/conjured_lightning",
        "spells/fiery_obliteration",
        "spells/into_battle",
        "spells/medusa_shield",
        "spells/murder",
        "spells/power_of_the_eclipse",
        "spells/sea_storm",
        "spells/sunray",
        "spells/sword_of_the_crusader",
        "spells/technology",
        "spells/thunder"
    };
}
