name: cards
services:
  db:
    image: "mysql:8.4.0"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    volumes:
      - /home/destroflyer/cards/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      retries: 0
    restart: always
  db-ui:
    build:
      dockerfile: db-ui.Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "33801:443"
    restart: always
  app:
    build:
      dockerfile: app.Dockerfile
    environment:
      DB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    ports:
      - "33800:33800"
    depends_on:
      db:
        condition: service_healthy
    restart: always